# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hush-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Koloda'
  pod 'Fakery'
  pod 'SwiftUIPager'
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'FLEX', :configurations => ['Debug']

end
