# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hush-SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PushNotifications'
  pod 'SDWebImageSwiftUI'
  pod 'Koloda'
  pod 'FBSDKLoginKit'
  pod 'Fakery'
  pod 'SwiftUIPager', '~> 1.4.0'
#  pod 'Alamofire', '~> 4.8.2'
  pod 'Alamofire', '~> 5.2.1'
#  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'SwiftyJSON', :git => 'https://github.com/tattn/SwiftyJSON.git', :branch => 'hotfix-xcode12'
  pod 'FLEX', :configurations => ['Debug']
  pod 'Purchases', '3.4.0'
end
