update_fastlane
default_platform(:ios)

platform :ios do
  desc "Upload Hush-SwiftUI to diawi."
  lane :diawi_upload do
    build_app(
      workspace: "../Hush.xcworkspace",
      scheme: "Hush-SwiftUI",
      silent: true,
      clean: true,
      export_options: {
        method: "ad-hoc"
      }
    )

    diawi(find_by_udid: false, wall_of_apps: false)
  end
end
