update_fastlane
default_platform(:ios)

platform :ios do
  desc "Upload Hush-SwiftUI to diawi."
  lane :diawi_upload do
    register_devices(
      devices: {
        "John Booker's iPhone XS" => "00008020-000D25422686002E"
      }
    )

    update_code_signing_settings(
      use_automatic_signing: true
    )

    build_app(
      workspace: "../Hush.xcworkspace",
      scheme: "Hush-SwiftUI",
      silent: true,
      clean: true,
      export_options: {
        method: "ad-hoc"
      }
    )

    diawi(find_by_udid: false, wall_of_apps: false)
  end
end
